services:
  mysql:
    image: mysql:8.4
    container_name: gestion-medicale-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gmdb
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=512M
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
